# Generated by Django 4.2.3 on 2023-07-22 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=31)),
                ('is_asset', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypeSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=31)),
                ('account_type', models.ManyToManyField(to='accounts.accounttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique account type name'),
        ),
        migrations.AddField(
            model_name='account',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.accounttypesubtype'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.accounttype'),
        ),
    ]
