# Generated by Django 4.2.3 on 2023-07-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_unique_account_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounttypesubtype',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
