# Generated by Django 4.2.3 on 2023-08-02 02:58

from django.db import migrations


def seed_data(apps, schema_editor):
    AccountType = apps.get_model("manual","AccountType")
    db_alias = schema_editor.connection.alias
    AccountType.objects.using(db_alias).bulk_create([
        AccountType(name="Cash Account", classification="Asset"),
        AccountType(name="Investment", classification="Asset"),
        AccountType(name="Cryptocurrency", classification="Asset"),
        AccountType(name="Real Estate", classification="Asset"),
        AccountType(name="Other", classification="Asset"),
        AccountType(name="Credit Card", classification="Liability"),
        AccountType(name="Mortgage", classification="Liability"),
        AccountType(name="Other", classification="Liability"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
