version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fira-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - node_modules:/workspace/node_modules
      - app_modules:/workspace/apps/fira-app/node_modules
      - sdk_modules:/workspace/libs/fira-api-sdk/node_modules
      - next:/workspace/apps/fira-app/.next
      - bin:/app/bin
    environment:
      POSTGRES_URL: postgres://postgres:docker@postgres:5432/fira?schema=public&sslmode=disable

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fira
      POSTGRES_PASSWORD: docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=fira --username=postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

volumes:
  node_modules:
  app_modules:
  sdk_modules:
  bin:
  next: