version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fira-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/fira
    environment:
      FIRA_MAILGUN_DOMAIN: ${FIRA_MAILGUN_DOMAIN}
      FIRA_MAILGUN_API_KEY: ${FIRA_MAILGUN_API_KEY}
