version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fira-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/client/node_modules
      - next:/app/client/.next
      - bin:/app/bin
volumes:
  node_modules:
  bin:
  next: