version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fira-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/workspace/node_modules
      - app_modules:/workspace/apps/fira-app/node_modules
      - sdk_modules:/workspace/libs/fira-api-sdk/node_modules
      - next:/workspace/apps/fira-app/.next
      - bin:/app/bin
volumes:
  node_modules:
  app_modules:
  sdk_modules:
  bin:
  next: