# fly.toml app configuration file generated for fira on 2023-05-06T19:37:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fira"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[build.args]
  NEXTAUTH_URL = "https://fira.opencorelabs.org"

[env]
  FIRA_BIND_HTTP = "0.0.0.0:8080"
  NODE_ENV = "production"
  NEXTAUTH_URL = "https://fira.opencorelabs.org"
