# Generated by Django 4.2.3 on 2023-07-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=31, max_digits=255),
        ),
    ]
