/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/token/pair': {
    /** Obtain Token */
    post: operations['3f863343_controller_obtain_token'];
  };
  '/api/token/refresh': {
    /** Refresh Token */
    post: operations['8c53b0cc_controller_refresh_token'];
  };
  '/api/token/verify': {
    /** Verify Token */
    post: operations['293284fd_controller_verify_token'];
  };
  '/api/accounts/register': {
    /** Create Account */
    post: operations['accounts_api_create_account'];
  };
  '/api/accounts/me': {
    /** Get Me */
    get: operations['accounts_api_get_me'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** TokenObtainPairOutputSchema */
    TokenObtainPairOutputSchema: {
      /** Email */
      email: string;
      /** Refresh */
      refresh: string;
      /** Access */
      access: string;
    };
    /** TokenObtainPairInputSchema */
    TokenObtainPairInputSchema: {
      /** Password */
      password: string;
      /** Email */
      email: string;
    };
    /** TokenRefreshOutputSchema */
    TokenRefreshOutputSchema: {
      /** Refresh */
      refresh: string;
      /** Access */
      access?: string;
    };
    /** TokenRefreshInputSchema */
    TokenRefreshInputSchema: {
      /** Refresh */
      refresh: string;
    };
    /** Schema */
    Schema: Record<string, never>;
    /** TokenVerifyInputSchema */
    TokenVerifyInputSchema: {
      /** Token */
      token: string;
    };
    /** Account */
    Account: {
      /** Email Address */
      email_address: string;
      /** Full Name */
      full_name: string;
      /** Verified */
      verified: boolean;
    };
    /** InputError */
    InputError: {
      /** Fields */
      fields: {
        [key: string]: string[] | undefined;
      };
      /** Message */
      message: string;
    };
    /** EmailPasswordRegistration */
    EmailPasswordRegistration: {
      /** Full Name */
      full_name: string;
      /** Email Address */
      email_address: string;
      /** Password */
      password: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  /** Obtain Token */
  '3f863343_controller_obtain_token': {
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenObtainPairInputSchema'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['TokenObtainPairOutputSchema'];
        };
      };
    };
  };
  /** Refresh Token */
  '8c53b0cc_controller_refresh_token': {
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenRefreshInputSchema'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['TokenRefreshOutputSchema'];
        };
      };
    };
  };
  /** Verify Token */
  '293284fd_controller_verify_token': {
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenVerifyInputSchema'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Schema'];
        };
      };
    };
  };
  /** Create Account */
  accounts_api_create_account: {
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailPasswordRegistration'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['InputError'];
        };
      };
    };
  };
  /** Get Me */
  accounts_api_get_me: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
    };
  };
}
