/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/accounts/register': {
    /** Create Account */
    post: operations['accounts_api_create_account'];
  };
  '/api/accounts/verify': {
    /** Verify Account */
    post: operations['accounts_api_verify_account'];
  };
  '/api/accounts/login': {
    /** Login */
    post: operations['accounts_api_login'];
  };
  '/api/accounts/me': {
    /** Get Me */
    get: operations['accounts_api_get_me'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Account */
    Account: {
      /** Email Address */
      email_address: string;
      /** Full Name */
      full_name: string;
      /** Verified */
      verified: boolean;
    };
    /** InputError */
    InputError: {
      /** Fields */
      fields: {
        [key: string]: string[] | undefined;
      };
      /** Message */
      message: string;
    };
    /** EmailPasswordRegistration */
    EmailPasswordRegistration: {
      /** Full Name */
      full_name: string;
      /** Email Address */
      email_address: string;
      /** Password */
      password: string;
      /** Verification Url */
      verification_url: string;
    };
    /** EmailVerification */
    EmailVerification: {
      /** Resend To Email */
      resend_to_email: string;
      /** Verification Code */
      verification_code: string;
    };
    /** Token */
    Token: {
      /** Jwt */
      jwt: string;
    };
    /** EmailPasswordLogin */
    EmailPasswordLogin: {
      /** Email Address */
      email_address: string;
      /** Password */
      password: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  /** Create Account */
  accounts_api_create_account: {
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailPasswordRegistration'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['InputError'];
        };
      };
    };
  };
  /** Verify Account */
  accounts_api_verify_account: {
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailVerification'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['InputError'];
        };
      };
    };
  };
  /** Login */
  accounts_api_login: {
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailPasswordLogin'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['InputError'];
        };
      };
    };
  };
  /** Get Me */
  accounts_api_get_me: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
    };
  };
}
