# Generated by Django 4.2.3 on 2023-07-24 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('is_asset', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypeSubType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('account_type', models.ManyToManyField(to='core.accounttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique account type name'),
        ),
        migrations.AddField(
            model_name='account',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.accounttypesubtype'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accounttypesubtype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique account sub type name'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique user account names'),
        ),
    ]
