name: Fly Deploy
on:
  pull_request_target:
    branches:
      - main
jobs:
  approve: 
    runs-on: ubuntu-latest
    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [approve]
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config ./fly.dev.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
