name: Go tests

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          go mod download all
          go install gotest.tools/gotestsum@latest

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make ci-test

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: junit-out.xml
